characteristics =  {"Ala":{"CB": "aliphatic"},
                    "Arg":{"CB":"aliphatic", "CG":"aliphatic", "CD": "aliphatic", "NE": "donor", "NH1": "donor", "NH2":"donor"},
                    "Asn":{"OD1":"acceptor", "ND2":"donor"},
                    "Asp":{"OD1":"acceptor", "OD2":"acceptor"},
                    "Cys":{"SG":"aliphatic", "CB":"aliphatic"},
                    "Gln":{"OE1":"acceptor", "NE2":"donor"},
                    "Glu":{"OE1":"acceptor", "OE2":"acceptor"},
                    "His":{"CG":"aromatic", "ND1":"aromatic", "CD2":"aromatic", "CE1":"aromatic", "NE2":"aromatic","NE2":"don_acc", "NE1":"don_acc"},
                    "Ile":{"CB":"aliphatic", "CG1":"aliphatic", "CG2":"aliphatic", "CD1":"aliphatic"},
                    "Leu":{"CB":"aliphatic", "CG":"aliphatic", "CD1":"aliphatic", "CD2":"aliphatic"},
                    "Lys":{"CB":"aliphatic", "CG":"aliphatic", "CD":"aliphatic", "CE":"aliphatic", "NZ":"donor"},
                    "Met":{"CB":"aliphatic", "CG":"aliphatic", "SD":"aliphatic", "CE":"aliphatic"},
                    "Phe":{"CG":"aromatic", "CD1":"aromatic", "CD2":"aromatic", "CE1":"aromatic", "CE2":"aromatic", "CZ":"aromatic"},
                    "Pro":{"CB":"aliphatic", "CG":"aliphatic", "CD":"aliphatic"},
                    "Ser":{"OG":"don_acc"},
                    "Thr":{"OD1":"don_acc", "CD2":"aliphatic"},
                    "Trp":{"CG":"aromatic", "CD1":"aromatic", "CD2":"aromatic", "NE1":"aromatic", "CE2":"aromatic", "CE3":"aromatic", "CZ1":"donor", "CZ3":"donor", "CH":"donor", "NE1":"donor"},
                    "Tyr":{"CB":"aromatic", "CD1":"aromatic", "CD2":"aromatic", "CE1":"aromatic", "CE2":"aromatic", "CZ":"aromatic", "OH":"don_acc"},
                    "Val":{"CB":"aliphatic", "CG1":"aliphatic", "CG2":"aliphatic"},
                    "Gly":{}}

charges =  {"Arg":{"NE": 0.33, "NH1": 0.33, "NH2": 0.33},
                    "Asp":{"OD1":-0.5, "OD2":-0.5},
                    "Glu":{"OE1":-0.5, "OE2":-0.5},
                    "His":{ "ND1":1},
                    "Lys":{"NZ":1}}

